version: '3.7'
services:
  fw-gui:
    image: ibehren1/fw-gui:v1.1.0
    container_name: fw-gui
    ports:
      - 8080:8080/tcp
    restart: unless-stopped
    volumes:
      - data:/opt/fw-gui/data
volumes:
  data: